version: '3'
services:
  db:
    image: "mysql:8.0.19"
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
  
  # phpmyadmin:
  #   image: "phpmyadmin/phpmyadmin:latest"
volumes:
  db_data: {}